#!/usr/bin/env python
from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
from builtins import *

import argparse
import configparser

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="Generate config file for bgen splitting")
    parser.add_argument('file_location_conf', action='store', type=str, help='config for location of all bgen files by chromosome')
    parser.add_argument('splitfile', action='store', type=str, help='Predetermined split points (as generated by http://github.com/FINNGEN/chrsplit )')
    parser.add_argument('outfile', action='store', type=str, help='output configuation file')
    parser.add_argument('-build37', action='store_true',
                        help='Don\'t use chr in chromosome names')

    args = parser.parse_args()
    conf = configparser.ConfigParser()
    conf.read( args.file_location_conf)

    fileconf = { str(chr):conf.get('files', 'chr_{}'.format(chr))  for chr in range(1,24)}
    fileconf["X"] = fileconf["23"]
    chr_prefix ="chr"
    if( args.build37 ):
        chr_prefix =""

    with open(args.outfile,'w') as out:
        with open(args.splitfile) as splits:
            for line in splits:
                line = splits.readline().rstrip("\n").split()
                f = fileconf[line[0]]
                out.write( "\t".join([ fileconf[line[0]], chr_prefix+line[0], line[1], line[2] ]) + "\n" )
